
services:
  ventas-service:
    build:
      context: ./ventas-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${VENTAS_DATABASE_URL}
    depends_on:
      - db

  inventario-service:
    build:
      context: ./inventario-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${INVENTARIO_DATABASE_URL}
    depends_on:
      - db
      - mongodb

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=${AUTH_DATABASE_URL}
    depends_on:
      - db

  agent-service:
    build:
      context: ./agent-service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      - MODEL_ENDPOINT=${MODEL_ENDPOINT}
    depends_on:
      - mongodb

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
