apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: gestia-auth-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: global-config
              key: AUTH_DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: auth-service
  type: ClusterIP # NodePort (cambiar a NodePort para acceder desde un navegador web externo)

# # esto es para que kubernetes monitore el estado se usara en produccion

# livenessProbe:
#   httpGet:
#     path: /health
#     port: 8000
#   initialDelaySeconds: 3
#   periodSeconds: 10
# readinessProbe:
#   httpGet:
#     path: /ready
#     port: 8000
#   initialDelaySeconds: 3
#   periodSeconds: 10

# # esto es para limitar los recursos que puede consumir el contenedor se definira en produccion

# resources:
#   limits:
#     memory: "256Mi"
#     cpu: "500m"
#   requests:
#     memory: "128Mi"
#     cpu: "250m"
